name: Aggregate JSON Files

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub
          
      - name: Run aggregation script
        run: python .github/scripts/aggregate_json.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit changes
        run: |
          git config --local user.email "vcsolanki@github.com"
          git config --local user.name "Vishal Solanki"
          git add aggregated.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update aggregated JSON data"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
